version: '1.0'
services:
  postgresql:
    image: postgres:14.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "postgresql"
      POSTGRES_USER: "postgresql"
      POSTGRES_PASSWORD: "root"





